# Generated by Django 5.2.6 on 2025-10-05 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='OfertaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupos_totales', models.PositiveIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='home.ofertaclase')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('rating_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_cursando', to='home.carrera')),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_creadas', to='home.perfil'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('horario_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='home.horarioofertado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='home.perfil')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('estudiante', 'horario_ofertado')},
            },
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='ramos',
            field=models.ManyToManyField(related_name='ofertas', to='home.ramo'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_rating', models.DateTimeField(auto_now_add=True)),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_recibidos', to='home.perfil')),
                ('calificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_dados', to='home.perfil')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='home.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicación', models.DateTimeField(auto_now_add=True)),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='home.ramo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to='home.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('oferta_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='home.ofertaclase')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicados', to='home.perfil')),
                ('solicitud_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='home.solicitudclase')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.perfil')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ramo')),
            ],
            options={
                'verbose_name': 'Ramo Cursado',
                'verbose_name_plural': 'Ramos Cursados',
                'unique_together': {('perfil', 'ramo')},
            },
        ),
    ]
