# Generated by Django 5.2.6 on 2025-10-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='solicitudclase',
            old_name='fecha_publicación',
            new_name='fecha_publicacion',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='perfilramo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horarioofertado',
            name='dia',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'horario_ofertado'), name='unique_inscripcion'),
        ),
        migrations.AddConstraint(
            model_name='perfilramo',
            constraint=models.UniqueConstraint(fields=('perfil', 'ramo'), name='unique_perfil_ramo'),
        ),
    ]
