# Generated by Django 5.1.4 on 2025-10-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_cursando', to='courses.carrera'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ramos_cursados',
            field=models.ManyToManyField(blank=True, related_name='perfiles_que_cursaron', through='courses.PerfilRamo', to='courses.ramo'),
        ),
    ]
