# Generated by Django 5.2.6 on 2025-10-12 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ese nombre de usuario ya existe.'}, help_text='Solo letras, números o _', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Usa solo letras, números o guión bajo (_), sin espacios ni acentos.')], verbose_name='Nombre de usuario'),
        ),
    ]
