# Generated by Django 5.2.6 on 2025-10-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner_file',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
