# Generated by Django 5.2.6 on 2025-11-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_perfil_banner_file_perfil_foto_file'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription_accepted', 'Inscription Accepted')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, help_text="Acción que se realizó sobre esta notificación (ej: 'Aceptada', 'Rechazada')", max_length=200, null=True)),
                ('action_date', models.DateTimeField(blank=True, help_text='Fecha en que se realizó la acción', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creation_date'],
            },
        ),
    ]
