# Generated by Django 5.2.6 on 2025-11-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(help_text='Tipo de notificación. Debe coincidir con una estrategia registrada en el factory.', max_length=50),
        ),
    ]
