# Generated by Django 5.2.7 on 2025-10-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudclase',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20),
        ),
    ]
