# Generated by Django 5.2.6 on 2025-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_inscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aceptado'), (2, 'Rechazado'), (3, 'Cancelado'), (4, 'Completado')], default=0, verbose_name='Estado de la Inscripción'),
        ),
    ]
