# Generated by Django 5.2.6 on 2025-10-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaclase',
            name='ramos',
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='courses.ramo'),
        ),
    ]
