# Generated by Django 5.2.6 on 2025-11-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_ofertaclase_ramos_ofertaclase_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
