# Generated by Django 5.2.6 on 2025-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_ofertaclase_ramos_ofertaclase_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaclase',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Oferta pública'),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Oferta pública'),
        ),
    ]
