# Generated by Django 5.2.6 on 2025-11-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_ofertaclase_public_solicitudclase_public'),
        ('courses', '0005_rating_comentario'),
    ]

    operations = [
    ]
